openapi: 3.1.0
info:
  description: Contains all available API endpoints in this codebase
  version: 1.0.0
  title: Bank Argent API documentation
  termsOfService: http://swagger.io/terms/
servers:
  - url: http://localhost:3001/api/v1
    description: developpement server
security:
  - Bearer: []
tags:
  - name: Transactions Module
    description: Every request about transactions of user
paths:
  /accounts/transactions:
    get:
      tags:
        - Transactions Module
      summary: Get all user's transactions
      description: API for fetching all user's transactions
      operationId: getTransactions
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Return successfully user's accounts
          $ref: '#/components/responses/SuccessRequestAccounts'
        '404':
          $ref: '#/components/responses/Notfound'
        '500':
          $ref: '#/components/responses/ServerError'
  /accounts/{accountId}/transactions/{transactionId}:
    get:
      tags:
        - Transactions Module
      summary: Get info for a specific transaction
      description: API for fetching a specific transaction from its id
      operationId: showTransactionById
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          schema:
            type: string
          required: true
        - in: path
          name: accountId
          description: The id of the selected account
          required: true
          schema:
            type: string
        - in: path
          name: transactionId
          description: The id of the transaction
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Expected transaction
          $ref: '#/components/responses/SuccessRequestTransaction'
        '404':
          $ref: '#/components/responses/Notfound'
        '500':
          $ref: '#/components/responses/ServerError'
    patch:
      tags:
        - Transactions Module
      summary: Update details of a specific transaction
      description: API for updating the category or note of a specific transaction
      operationId: updateTransactionById
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          schema:
            type: string
          required: true
        - in: path
          name: accountId
          description: The id of the selected account
          required: true
          schema:
            type: string
        - in: path
          name: transactionId
          description: The id of the transaction
          required: true
          schema:
            type: string
      requestBody:
        description: user to update a transaction
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PartialUpdatedTransaction'
      responses:
        '200':
          description: Transaction updated successfully
          $ref: '#/components/responses/SuccessRequestTransaction'
        '404':
          $ref: '#/components/responses/Notfound'
        '500':
          $ref: '#/components/responses/ServerError'
components:
  securitySchemes:
    Bearer:
      type: http
      scheme: bearer
      bearerFormat: JWT
  responses:
    SuccessRequestTransaction:
      description: Fetching API successfully
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SuccessFetchingTransaction'
    SuccessRequestAccounts:
      description: Fetching API successfully
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SuccessFetchingAccounts'
    Notfound:
      description: The specified resource was not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    ServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
  schemas:
    Account:
      type: object
      required:
        - id
        - title
        - type
        - totalAmount
        - currency
        - listOfTransactions
      properties:
        id:
          type: string
          examples:
            - A10
        title:
          type: string
          examples:
            - Argent Bank Checking (x8349)
        type:
          type: string
          enum:
            - debit
            - credit
          examples:
            - debit
        totalAmount:
          type: number
          format: double
          examples:
            - 2082.79
        currency:
          type: string
          examples:
            - $
        listOfTransactions:
          $ref: '#/components/schemas/ListOfTransactions'
    ListOfAccounts:
      type: array
      items:
        $ref: '#/components/schemas/Account'
      examples:
        - id: A10
          type: debit
          title: Argent Bank Checking (x8349)
          totalAmount: 11189.37
          currency: $
          listOfTransactions:
            - id: 1
              type: debit
              date: '2024-07-01'
              description: Electrolux
              amount: 10928.42
              balance: 12117.79
              transactionType: electronic
            - id: 2
              type: credit
              date: '2024-07-04'
              description: Electrolux
              amount: 928.42
              balance: 11189.37
              transactionType: electronic
    TransactionSummary:
      type: object
      required:
        - id
        - type
        - date
        - description
        - amount
        - balance
        - transactionType
      properties:
        id:
          type: integer
          examples:
            - 1
        type:
          type: string
          enum:
            - debit
            - credit
          examples:
            - debit
        date:
          type: string
          format: date
          examples:
            - '2024-07-01'
        description:
          type: string
          examples:
            - Grocery shopping
        amount:
          type: number
          format: double
          examples:
            - '150.75'
        balance:
          type: number
          format: double
          examples:
            - 12117.79
        transactionType:
          type: string
          examples:
            - electronic
      examples:
        - id: 1
          type: debit
          date: '2024-07-01'
          description: Electrolux
          amount: 10928.42
          balance: 12117.79
          transactionType: electronic
    Transaction:
      type: object
      required:
        - id
        - type
        - date
        - description
        - amount
        - balance
        - transactionType
      properties:
        id:
          type: integer
          examples:
            - 1
        type:
          type: string
          enum:
            - debit
            - credit
          examples:
            - debit
        date:
          type: string
          format: date
          examples:
            - '2024-07-01'
        description:
          type: string
          examples:
            - Grocery shopping
        amount:
          type: number
          format: double
          examples:
            - '150.75'
        balance:
          type: number
          format: double
          examples:
            - 12117.79
        transactionType:
          type: string
          examples:
            - electronic
        transactionDetails:
          type: object
          properties:
            category:
              type:
                - string
                - 'null'
              enum:
                - food
                - insurance, health
                - transport
                - leisure
            note:
              type:
                - string
                - 'null'
              maxLength: 150
      examples:
        - id: 1
          type: debit
          amount: 928.42
          date: '2024-07-01'
          description: Grocery shopping
          transactionType: Carrefour
          transactionDetails:
            category: food
            note: food of July month
    ListOfTransactions:
      type: array
      items:
        $ref: '#/components/schemas/TransactionSummary'
      examples:
        - id: 1
          type: debit
          date: '2024-07-01'
          description: Electrolux
          amount: 10928.42
          balance: 12117.79
          transactionType: electronic
        - id: 2
          type: credit
          amount: 184.3
          date: '2024-07-02'
          description: EDF
          balance: 13760.93
          transactionType: electronic
    PartialUpdatedTransaction:
      type: object
      properties:
        category:
          type: string
          enum:
            - food
            - insurance, health
            - transport
            - leisure
        note:
          type: string
          maxLength: 150
      examples:
        - category: transport
          note: train to Busan
    Error:
      type: object
      properties:
        status:
          type: integer
        message:
          type: string
    SuccessFetchingTransaction:
      type: object
      properties:
        status:
          type: integer
        message:
          type: string
        body:
          type: object
          $ref: '#/components/schemas/Transaction'
    SuccessFetchingAccounts:
      type: object
      properties:
        status:
          type: integer
        message:
          type: string
        body:
          type: object
          $ref: '#/components/schemas/ListOfAccounts'
